version: '3'
services:
    app:
        image: auditbigdatasample/app
        ports:
        - 80:80
        environment:
        - UploadUrl=Uploads
        - DOTNET_ENVIRONMENT=DockerAuditClickhouse
        - BackendRoot=http://localhost
        networks:
        - audit-sample
        
    audit-odata-backend:
        image: auditbigdatasample/auditodatabackend
        ports:
        - 6505:6505
        environment:
        - DOTNET_ENVIRONMENT=DockerAuditClickhouse
        - ASPNETCORE_URLS=http://+:6505
        networks:
        - audit-sample
      
    postgres-db:
        image: auditbigdatasample/postgres
        volumes:
        - DB:/var/lib/pgsql/data/
        ports:
        - 5432:5432
        networks:
        - audit-sample
    
    clickhouse-db:
        image: auditbigdatasample/clickhouse
        command: gosu clickhouse:clickhouse sh -c ' while :; do /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml; sleep 1; done'
        volumes:
        - clickhousedb:/var/lib/clickhouse
        ports:
        - 8123:8123
        - 9000:9000
        networks:
        - audit-sample

volumes:
  clickhousedb:
  DB:
networks:
  audit-sample:
