version: '3'
services:
    app:
        image: auditbigdatasample/app
        ports:
        - 80:80
        environment:
        - UploadUrl=Uploads
        - DOTNET_ENVIRONMENT=DockerAuditPostgres
        - BackendRoot=http://localhost
        networks:
        - audit-sample
        
    audit-odata-backend:
        image: auditbigdatasample/auditodatabackend
        ports:
        - 6505:6505
        environment:
        - DOTNET_ENVIRONMENT=DockerAuditPostgres
        - ASPNETCORE_URLS=http://+:6505
        networks:
        - audit-sample
      
    postgres-db:
        image: auditbigdatasample/postgres
        volumes:
        - DB:/var/lib/pgsql/data/
        ports:
        - 5432:5432
        networks:
        - audit-sample

volumes:
  DB:
networks:
  audit-sample: