import FlexberrySampleAuditBigDataClass4EController from '../flexberry-sample-audit-big-data-class4-e';

var FlexberrySampleAuditBigDataClass4ENewController = FlexberrySampleAuditBigDataClass4EController;
export default FlexberrySampleAuditBigDataClass4ENewController;
