import FlexberrySampleAuditBigDataClass1EController from '../flexberry-sample-audit-big-data-class1-e';

var FlexberrySampleAuditBigDataClass1ENewController = FlexberrySampleAuditBigDataClass1EController;
export default FlexberrySampleAuditBigDataClass1ENewController;
