import FlexberrySampleAuditBigDataClass2EController from '../flexberry-sample-audit-big-data-class2-e';

var FlexberrySampleAuditBigDataClass2ENewController = FlexberrySampleAuditBigDataClass2EController;
export default FlexberrySampleAuditBigDataClass2ENewController;
