version: '3.2'

services:
  clickhouse:
    image: auditbigdatatest/clickhouse
    command: gosu clickhouse:clickhouse sh -c ' while :; do /usr/bin/clickhouse-server --config-file=/etc/clickhouse-server/config.xml; sleep 1; done'
    volumes:
      - clickhousedb:/var/lib/clickhouse

    ports:
      - 8123:8123
      - 9000:9000
      
  app-postgres-db:
    image: auditbigdatatest/postgres
    volumes:
      - DB:/var/lib/pgsql/data/
    ports:
      - 5432:5432

volumes:
  clickhousedb:
  DB: